{{- if .Values.gateway.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: docker-example-gw
  namespace: istio-system
spec:
  selector:
    istio: istiogateway
  servers:
    - port:
        number: 8081
        name: http-8081
        protocol: HTTP
      hosts:
        - "*"
  {{- end }}
