{{- if .Values.gateway.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: docker-example-gw
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: docker-example
        protocol: HTTP
      hosts:
        - "*"
  {{- end }}
