{{- if .Values.virtualservice.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: docker-example-vs
spec:
  hosts:
    - "docker-example.com"
  gateways:
    - docker-example-gw
  http:
    - match:
        - uri:
            prefix: "/"
      route:
      - destination:
          host: docker-example.default.svc.cluster.local
          port:
            number: 80
  {{- end }}
